### ISSUE TITLE
Type definitions are not loaded on startup

### ISSUE THREAD

**Issue by Globidev** [rvion/CushyStudio#11]
When opening a cushy workspace, the types won't be correctly resolved until the `cushy.d.ts` file is manually open

https://user-images.githubusercontent.com/2079561/232311012-263feb21-0a81-41f8-a585-48a74b1ea29c.mp4

**Comment by rvion** [comment]
🙌 ! thanks, the trick is to add `/// <reference path="cushy.d.ts" />` at the top of the file; 

i'm currently working on this very specific area; 
- I'll split the types again in two or three files
- move them in a .cushy folder along cache folder

**Comment by rvion** [comment]
I attempted to fix this by generating some `tsconfig.json` not quite sure this is enough. it kinda work on my end, so I'll close it for now, but let's just re-open this issue if something doesn't work
