### ISSUE TITLE
windows and linux: installed standalone node.js not in system path

### ISSUE THREAD

**Issue by frankyifei** [rvion/CushyStudio#126]
I tried crushystudio on windows 11 and ubuntu. I don't have node.js installed on both systems before I try. Both are having problems running. The issues are from not adding the embedded node.js in system path. I had to manually add a line in starting bat or sh file to start it. 
on windows even the _windows-install.bat need this line after line 54 to finish installation. "SET PATH=$PATH;%NODE_INSTALL_DIR%"

_windows-start.bat needs this line after line 10 to start "SET PATH=$PATH;%~dp0\.cushy\node\v18.19.0-win-x64\node-v18.19.0-win-x64" , The node path has to be hardcoded, I have no idea how to find the node.js folder in bat file.

**Comment by rvion** [comment]
thanks ! will look at that today

**Comment by rvion** [comment]
I think it's fixed; both in start, install, and update.
I also simplified the install script a bit and dropped support for x86 arch. I think everyone nowdays use windows 64 bit.

**Comment by rvion** [comment]
also, since the PATH patching is only taken into account for the script duration, i did 

`SET PATH=%NODE_INSTALL_DIR%;$PATH`

instead of 

`SET PATH=$PATH;%NODE_INSTALL_DIR%`

**Comment by frankyifei** [comment]
works well now
