### ISSUE TITLE
Design concerns about the `ask*` API

### ISSUE THREAD

**Issue by Globidev** [rvion/CushyStudio#13]
Right now it seems that we're queuing a "step" for each ask request and popping them in LIFO fashion
This makes the following workflow behave rather unexpectingly:
```ts
WORKFLOW('multi-ask', async (_graph, flow) => {
    const aOrB = await Promise.race([
        flow.askBoolean('A').then(() => 'A'), 
        flow.askBoolean('B').then(() => 'B')
    ])
    flow.print(aOrB)
})
```
We correctly get 2 sets of buttons, but no matter which one is clicked, `B` is always printed (it was created last and therefore is popped first)

As a possibly related issue, clicking a button that was displayed during a previous run will also resolve the ask step from the current run

**Comment by rvion** [comment]
Those `askApis` went away completely (in master; unreleased) in favor of a newer ask() api that does things way better.
but problem remains for now. 

I'll add a proper requestID soon. 
I'm delaying this for now because I'm waiting for some extra infos from ComfyUI server

**Comment by rvion** [comment]
asked* apis have been removed for now, closing :)
