### ISSUE TITLE
Flow Summary and Image Output Area Empty

### ISSUE THREAD

**Issue by M1kep** [rvion/CushyStudio#15]
Currently the output window goes completely blank on every run. Once I close the pane, and re-run the workflow, it flashes some output for a moment and then goes blank until I close it again. This feels possibly related to the flow summary as this behavior used to only happen when I attempted to generate a flow summary.

**Comment by rvion** [comment]
thanks ! looking into it

**Comment by rvion** [comment]
this should be fixed / no longer relevant since the rewrite
