### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by Delicious-Bacon** [rvion/CushyStudio#194]
## Clean uninstall
I went in and ran the `_mac-linux-install.sh` which installed Node and other dependencies.

Let's say I want to uninstall it now, how would I do it to remove everything that installed with the script? I am aware of the `_mac-linux-cleanup.sh`, but that removes things just in the project:
```sh
set -eu
rm -rf node_modules
rm -rf .cushy
```

Node installed globally. What else is there?

---
## Had an error

Also had this error on boot:
```
$ ./_mac-linux-start.sh 
Starting Vite with Electron's Node...
Server running on http://localhost:8688
waiting for cushy to start
[VITE] vite started
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Warning: loader_get_json: Failed to open JSON file intel_hasvk_icd.x86_64.json
Warning: /usr/lib64/libvulkan_intel.so: cannot open shared object file: Permission denied
Warning: loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib64/libvulkan_intel.so. Ignoring this JSON
Warning: loader_get_json: Failed to open JSON file lvp_icd.x86_64.json
Warning: /usr/lib64/libvulkan_radeon.so: cannot open shared object file: Permission denied
Warning: loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib64/libvulkan_radeon.so. Ignoring this JSON
Warning: loader_get_json: Failed to open JSON file nvidia_icd.x86_64.json
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
```

```
Operating system: linux -> Rocky Linux 9
Architecture: x86_64
Node.js architecture: linux-x64
Node.js version: v18.19.0
```

The CushyDiffusion didn't work.

**Comment by rvion** [comment]
Yeah, this is still a bit early; lots of polish & docs to come soon :)

Cushy is portable. Nothing have been installed outside of the folder. You can just delete the folder to "uninstall"

**Comment by rvion** [comment]
Install script install node locally in the .cushy subfolder

**Comment by Delicious-Bacon** [comment]
> also, if you have libva error on your linux, it's a driver issue; should affect all electron apps; re-installing libva related packages should fix. also possible to launch cushy without hardware acceleration (e.g. --disable-gpu)

Hmm, I have both `libva` and `libva-devel` installed...

**Comment by Delicious-Bacon** [comment]
@birdddev 
> Do you have the vulkan/vaapi drivers for your gpu? For example, on Arch I need `vulkan_radeon libva-mesa-driver` for vulkan and vaapi with AMD on top of `libva`.

Why is it asking for vulkan drivers when the server has Nvidia?

@rvion 
> So did I when I first had this issue a few monthes ago; did some google, ran some install command, and it went away.

So what's the command...?

**Comment by rvion** [comment]
> So what's the command...?
Can't remember; we should definitively open an other issue specifically related to libva;
