### ISSUE TITLE
Providing functionality that supports backend operations on the cloud.

### ISSUE THREAD

**Issue by ltdrdata** [rvion/CushyStudio#21]
Many individuals utilize ComfyUI in the cloud, for example, Google Colab. In my opinion, if CushyStudio could also support this backend, it would enable more people to use this tool.

**Comment by rvion** [comment]
but I also agree that lots of administration features are missing. I really would love if cushy could setup everything needed on its own. Some config stanza at the beginning of cushy scripts to list script dependencies (models, custom_nodes, modified default values, etc) would be perfect.

**Comment by rvion** [comment]
fixed
