### ISSUE TITLE
how to import from ComfyUI images

### ISSUE THREAD

**Issue by gomaxlou** [rvion/CushyStudio#22]
could you post some code or video?  3q

**Comment by rvion** [comment]
yes, I'll add them soon! thanks for asking !

For now, you have to have either a `ComfyUI png image`, or a `workflow.json` file in your workspace and open.

then you can open the command palette (ctrl+shift+p on windows) and type cushy import
it will create a corresponding script right beside.

import works well, but generated code is a bit verbose. 

lots of improvements are on the way. 

I'll leave this open until things are better

**Comment by rvion** [comment]
Cushy has been rewritten since. documentation is still lacking, but 
you can now import any ComfyUI images or workflow by dropping them in the `actions` folder at the root of the repository
