### ISSUE TITLE
electron exited with signal SIGSEGV

### ISSUE THREAD

**Issue by ProtoBelisarius** [rvion/CushyStudio#233]
Installed per instructions, but unable to start, only get the error as mentioned in the title:

`/home/USERNAME/Git/CushyStudio/node_modules/electron/dist/electron exited with signal SIGSEGV`

full terminal output during install:
```
./_mac-linux-install.sh

Operating system: linux
Architecture: x86_64
Node.js architecture: linux-x64
Node.js version: v18.19.0
Download URL: https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.gz
Current working directory: /home/USERNAME/Git/CushyStudio
Extraction directory: /home/USERNAME/Git/CushyStudio/.cushy/node/v18.19.0-linux-x64
No existing Node.js installation found in /home/USERNAME/Git/CushyStudio/.cushy/node/v18.19.0-linux-x64. Proceeding with installation.
Downloading Node.js v18.19.0 for x86_64 FROM https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.gz ...
Installing npm with curl...
Node.js has been installed in /home/USERNAME/Git/CushyStudio/.cushy/node/v18.19.0-linux-x64
NPM binary path: /home/USERNAME/Git/CushyStudio/.cushy/node/v18.19.0-linux-x64/bin/npm
Node binary path: /home/USERNAME/Git/CushyStudio/.cushy/node/v18.19.0-linux-x64/bin/node
Installing dependencies...

> cushystudio@0.0.99 postinstall
> patch-package

patch-package 8.0.0
Applying patches...
@react-three/drei@9.105.5 ✔
meshline@3.1.7 ✔

added 925 packages, and audited 926 packages in 3m

137 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
  • electron-builder  version=24.13.3
  • rebuilding native dependencies  dependencies=better-sqlite3@9.6.0 platform=linux arch=x64
  • install prebuilt binary  name=better-sqlite3 version=9.6.0 platform=linux arch=x64 napi=
[BUILD] 1. build js
[BUILD] (NO minify)
[BUILD] []
[BUILD] []
[BUILD] 2. build css 
Tailwind CSS build complete.
index.html: 909 bytes
main.css: 47042 bytes
main.js: 13872619 bytes
meta.json: 1696919 bytes
output.css: 190971 bytes
🟢 cushy-install.sh completed successfully.

./_mac-linux-start.sh

Starting Vite with Electron's Node...
[🤠] process.platform = linux
waiting for cushy to start
API server running on http://localhost:8688
/home/USERNAME/Git/CushyStudio/node_modules/electron/dist/electron exited with signal SIGSEGV
```

**Comment by ProtoBelisarius** [comment]
And yes, it does start successfully when using `./_mac-linux-start-dev.sh`
Which environment variable are you referring to?

**Comment by birdddev** [comment]
The platform something = auto.
I think possibly during the explicit sync craze, something got bugged out for amd gpus. As when I do screenshares now, people tell me that it stutters like how the nvidia gpu's would render frames out of order pre-explicit sync.
but I haven't tested any of this, it could also be anywhere in the chain though. No idea how to begin debugging it and it probably isn't even because of us since it seems to work for others fine. 😔

**Comment by ProtoBelisarius** [comment]
Thank you very much. 

And yea, this does seem really weird. I generally don't have any problems with wayland, only for GIMP on wayland, where dragging in images causes a total crash. But well, GIMP problems, my fault for trying to use this train wreck.

**Comment by birdddev** [comment]
Glad I could help with this super niche issue lmao, it does also narrow down where it could lie, so thanks for the report.

There is another issue to look out for, when drag n dropping images from within different parts of the program on Wayland it will hang/crash unless something has a proper consumer for the drop.

Every electron app I've used has had awful drag n dropping on Wayland though tbh, at least on KDE. I haven't tested anything else. They seem to stop accepting inputs unless you drag another file and then drag it back out, really annoying with Discord and when I was using comfy with chromium app mode. I just copy and paste whenever possible now, lmao.
