### ISSUE TITLE
Incorrect filesystem paths for vscode file URIs

### ISSUE THREAD

**Issue by neecapp** [rvion/CushyStudio#27]
## Issue

Import flow fails on non-nix systems.

Other functionality may be impacted, this was the only place immediately apparent.

## Solution

In multiple places, `vscode.Uri.file(<path>).path` is used to get the filesystem path; however, [`vscode.Uri.file(<path>).fsPath`](https://github.com/microsoft/vscode-uri/blob/b54811339bd748982d0e2697fa857a3fecc72522/src/uri.ts#L180-L209) should be used instead.

Example: [`Workspace#importCurrentFileAsComfyUIPNG`](https://github.com/rvion/CushyStudio/blob/dc8e05de4c0996e87d91f10df7d18787a8b48f72/src/core-back/Workspace.tsx#L367) uses 
`const relPathStr = vscode.Uri.file(absPath).path.replace(this.wspUri.fsPath, '.')`. The `this.wspUri.fsPath` is correct; however, `vscode.Uri.file(absPath).path` is not. This causes the replace to fail and thus the import to fail. Switching to `vscode.Uri.file(absPath).fsPath` fixes this issue.

The same issue is present in [`Workspace#importCurentFileAsComfyJSON`](https://github.com/rvion/CushyStudio/blob/dc8e05de4c0996e87d91f10df7d18787a8b48f72/src/core-back/Workspace.tsx#L335).

**Comment by rvion** [comment]
thanks ! I think I fixed it already in some dev branch.
The repo is going though a massive improvement. news very soon

**Comment by neecapp** [comment]
Look forward to the coming upgrades. Great work on the project so far, thanks for sharing.

**Comment by rvion** [comment]
I think this can be fixed, since the project is not based on vscode anymore, and has been rewritten since
