### ISSUE TITLE
Hanging on `await flow.PROMPT()`

### ISSUE THREAD

**Issue by bavellone** [rvion/CushyStudio#28]
Using `rvion.cushystudio-0.0.99.vsix` and the current example given in the README, I'm not getting any output past the `await flow.PROMPT()` line (e.g. adding `flow.showHTMLContent('TEST')` to the next line does nothing). I'm not seeing any images either, although I do see them being generated in the ComfyUI output directory.

Seems like the completion event for the image generation isn't being sent/received correctly? 

Here's the output log when it's hanging:
```
ℹ️ found WORKFLOW demo-1
ℹ️ 🔥 seed: 19040996
ℹ️ prompt requested
ℹ️ checkpoint:{"1":{"class_type":"CheckpointLoaderSimple","inputs":{"ckpt_name":"deliberate_v2.safetensors"}},"2":{"class_type":"EmptyLatentImage","inputs":{"width":512,"height":512,"batch_size":1}},"3":{"class_type":"CLIPTextEncode","inputs":{"text":"masterpiece, (chair:1.3)","clip":["1",1]}},"4":{"class_type":"CLIPTextEncode","inputs":{"text":"","clip":["1",1]}},"5":{"class_type":"KSampler","inputs":{"model":["1",0],"seed":19040996,"steps":20,"cfg":10,"sampler_name":"euler","scheduler":"normal","positive":["3",0],"negative":["4",0],"latent_image":["2",0],"denoise":0.8}},"6":{"class_type":"VAEDecode","inputs":{"samples":["5",0],"vae":["1",2]}},"7":{"class_type":"SaveImage","inputs":{"images":["6",0],"filename_prefix":"ComfyUI"}}}
ℹ️ sending prompt to http://localhost:8188/prompt
```

Let me know if I can help debug in any way, I'd love to get this project working for me and love what you're doing here!

**Comment by rvion** [comment]
Thanks, I've been busy with life lately, but the project has been mostly rewritten and is now way better. I just took some time to focus on work and familly, but I really want to release the new version soon . Can you ping me on discord?

**Comment by rvion** [comment]
this should have been fixed since rewrite :)
still have to remove the old vscode extension, though x)
