### ISSUE TITLE
doc issue?

### ISSUE THREAD

**Issue by drscotthawley** [rvion/CushyStudio#30]
I ran 
```
git clone https://github.com/rvion/CushyStudio
cd CushyStudio
npm install
npm start
```

And I got this:
<img width="1013" alt="Screenshot 2023-10-09 at 7 09 20 PM" src="https://github.com/rvion/CushyStudio/assets/13925685/9f0d3465-f141-420d-8ad9-c75f193e49e4">

Are there some missing instructions, e.g. "Install ComfyUI first"?  
N00bs gonna n00b.

**Comment by rvion** [comment]
100% agree, doc is absolutely inexistant right now, and lots of basic usability stuff are missing; working on adding those asap :)

**Comment by rvion** [comment]
not perfect, but should help a bit 🙃
