### ISSUE TITLE
Doesn't work with vid2qr2vid animatediff workflow, fails to parse

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#31]
Hi, see the attached workflow

[vid2qr2vid_v2.json](https://github.com/rvion/CushyStudio/files/12885992/vid2qr2vid_v2.json)

![RoundedScreen_OZUK7xNOZX](https://github.com/rvion/CushyStudio/assets/3945277/e6fa2242-94f5-4589-9f29-22d985025d40)

**Comment by rvion** [comment]
I'll take a look, thanks for the report

**Comment by rvion** [comment]
I think I've fixed it; not 100% sure yet. not diving much more now, as video is going to be the focus of the coming days
