### ISSUE TITLE
Suggestion: display a tooltip with the relevant file path when hovering special tokens in the prompt box (embeddings, lora, wildcard, ...) with the mouse

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#59]
Super useful, more productivity, fuck yea. Knock two birds with one stone by making it so holding SHIFT turns them clickable to open the directory. A power user's delight 👌

**Comment by rvion** [comment]
https://github.com/rvion/CushyStudio/assets/2150990/bb3d352d-040f-41ac-b212-7d3b7a10aa8c

not quite sure if this issue is done, 70% done, or 130% done 😄
closing just in case, but feel free to re-open it with any specific demand like specific behaviour for specific rich prompt tokens

**Comment by oxysoft** [comment]
Not pulling any punches I see, proper productivity oriented UI. Nice.

**Comment by oxysoft** [comment]
Wait, it seems to be missing the the path to file on disk @rvion
