### ISSUE TITLE
Consider creating a stable branch

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#60]
In the past I tried CushyStudio a month or two and gave up on it because I couldn't seem to get ahold of a working commit. Right now I am trying it again and wow it's impressive, keep up the great work folks, finally we are starting to get real production-grade software. However even though it worked fine, certain things seem very WIP or bleeding edge, so I think a stable branch could could save some superfluous tickets and improve the adoption further!

**Comment by rvion** [comment]
<img width="396" alt="image" src="https://github.com/rvion/CushyStudio/assets/2150990/971fa20f-d679-4ebd-8358-89cbd07c760d">

will release that this evening when I'm back from work

**Comment by rvion** [comment]
it's technically done; but now I need to manage to convince myself to only commit in dev branch, and perdiodically merge into master 😄; maybe I'll make the switch this weekend

----

![image](https://github.com/rvion/CushyStudio/assets/2150990/bfad0720-0dcb-48dd-8cc6-4aca2d76ab43)
https://xkcd.com/1428/

**Comment by ricklove** [comment]
@rvion This is pretty important. CushyStudio has a great description, but alot of stuff is broken in a clean install. I mainly want to create my own app, and I haven't gotten anything to work yet.

**Comment by rvion** [comment]
yup, you were right :)
dev branch is here, and is here to stay; 
I will now expect all PR to be against the dev branch, dev will be merged periodically into master
