### ISSUE TITLE
Lora popup: should not auto-disappear when the cursor leaves if it has focus

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#75]
#59 introduced a new popup for loras and it's very useful, but if you click into the input fields and let go of the mouse to enter values, it will disappear if the mouse accidentally leaves goes out of the popup's bounds.

Instead it should remain open if I have clicked anywhere into the popup and require clicking outside to close it.

**Comment by rvion** [comment]
I fixed that; it's not yet documented, but **right-clicking any tooltip handle make the tooltip persistently visible**
