### ISSUE TITLE
Checkpoint dropdown list doesn't fit with 'dense' layout

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#76]
If I enable the mobile layout, the dropdown list with all my SD checkpoints feels good, but in the dense layout it seems out of the place, too airy compared to the rest of the UI. I also feel that the list could be a lot longer, imo it's fine to take up the whole available vertical space up to the window bounds.

**Comment by rvion** [comment]
Can you send a screenshot ?

**Comment by rvion** [comment]
the new "auto" layout is now way better, and probably completely subsume the dense layout.

if you really want to force everything on a single line with the dense layout, I've also made a few improvements, especially on dropdowns

![image](https://github.com/rvion/CushyStudio/assets/2150990/5110abe6-de1f-4e6c-96ad-2ef862dca966)
