### ISSUE TITLE
Add hover tooltips to each toolbar menu items

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#77]
Hover tooltip on all of these which also contains information about what you can do with each of the functionality or window.

For example the Civitai tooltip can specify that it's simply offered as a shortcut to the civitai website and it doesn't offer any fancy integration or features other than that. Thus these tooltips help to cut down on confusion as well as better communicate the capabilities and usage patterns of the application.

![image](https://github.com/rvion/CushyStudio/assets/3945277/6f489c52-289d-4055-9865-fde725d7ec89)

Note: the tooltip should be proper minimal tooltips, not the distracting popup balloon as we currently have with the Actions button. I also suggest replacing that ballon with the proper tooltip suggested here.

**Comment by rvion** [comment]
fixed

![image](https://github.com/rvion/CushyStudio/assets/2150990/3a524913-10e8-4278-9bdc-51453dd3346d)
