### ISSUE TITLE
Suggestion: rename 'Actions' button to 'Library'

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#78]
I think _Actions_ is too vague, it's not clear which actions we are talking about as it could also be the actions I already have open i.e. my tabs. _Library_ on the other hand connects it to the folder and makes it clear that it's the template not yet loaded into a buffer to use it.

![image](https://github.com/rvion/CushyStudio/assets/3945277/492039c9-3699-4735-945f-12cb84c298f6)

**Comment by rvion** [comment]
yes

**Comment by rvion** [comment]
![image](https://github.com/rvion/CushyStudio/assets/2150990/50d6bff1-8e89-46d8-85b3-c0a1fb143a43)

also made it slightly bigger
