### ISSUE TITLE
Bring back library as a tool window

### ISSUE THREAD

**Issue by oxysoft** [rvion/CushyStudio#79]
I like the new library, but why is it a huge modal window on top of the window app? I think it would be much more convenient if that whole UI were embedded into a tool window like the rest. I think both have their place depending on the context, but for default use I prefer it be non-blocking,

**Comment by rvion** [comment]
yes

**Comment by rvion** [comment]
https://github.com/rvion/CushyStudio/assets/2150990/42b32fd0-b97e-404c-9935-44901189436d

click on `Fix Layout` to add it  by default
