### ISSUE TITLE
Can't start dev server

### ISSUE THREAD

**Issue by GaidamakUA** [rvion/CushyStudio#8]
Failed to load resource: the server responded with a status of 404 (Not Found)
Logger.ts:54 [INFO] monaco ready
Logger.ts:54 [INFO] typescript ready (4.5.5)
chunk-RCPA6UVN.js:1 Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at chunk-RCPA6UVN.js:1:542
    at new Promise (<anonymous>)
    at c (chunk-RCPA6UVN.js:1:397)
    at a (chunk-HNLFKTAJ.js:1:68)
    at Module.o (chunk-J5WVX3SY.js:3:29)
    at CushyStudio.CREATE (CushyStudio.ts:23:49)
    at AppUI.tsx:22:42
    at mountMemo (react-dom.development.js:17225:19)
    at Object.useMemo (react-dom.development.js:17670:16)
    at useMemo (react.development.js:1650:21)
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by rvion** [comment]
How did you start the dev server ?

Did you type `pnpm dev`

You should **not** open the web client in a regular browser, but let the rust shell open it automatically. 

Could you share a screenshot of your error ?

**Comment by GaidamakUA** [comment]
@rvion yes, I did type pnpm dev
How do I run rust shell?

**Comment by rvion** [comment]
![image](https://user-images.githubusercontent.com/2150990/229371179-fc87cd7c-8ad0-43b8-a945-903147c6b1c5.png)

it should start automatically; you must not click on the link http://127.0.0.1:5173/, and just wait for a window to appear.

the very first time, it will compile quite a few rust libraries, so it might takes some time, but after, it should start pretty quickly even after a git pull

**Comment by rvion** [comment]
![image](https://user-images.githubusercontent.com/2150990/229371264-3aa42a5e-c23a-47cb-91a7-7fcab5a1e461.png)

do you see the `Building [======>. ] xxx/360: CushyStudio(bin)` ?

**Comment by rvion** [comment]
the whole codebase has been rewritten as a vscode extension, closing because this is no longer relevant
