### ISSUE TITLE
Feature Request: Multiple independent prompts

### ISSUE THREAD

**Issue by ricklove** [rvion/CushyStudio#87]
All the examples have a single `await flow.PROMPT()` at the end of run (or in a loop with a single value change):

```
        //        👇 for every value
        for (const i of [1, 2, 3]) {
            //                 👇 we patch the postive text
            positive.json.inputs.text = `a house ${i}`
            //        👇 and re-run the prompt
            await flow.PROMPT()
        }
```

However, I want to create a **new graph** after awaiting a prompt (instead of looping over and reusing an existing one).

Is there any possible way to do this?

- is there a command to get a new blank graph
- otherwise is there a way to delete all the nodes from the existing graph

**Comment by ricklove** [comment]
Ok, it looks like disabling all the nodes of the current workflow works. Disabled nodes are not sent in the next prompt, but they are still around to receive state changes for a running prompt etc.

```

        // ...  Build first graph
        // Run first graph
        const result = await flow.PROMPT();

        // Disable all nodes
        flow.workflow.nodes.forEach((x) => x.disable());

        // Build new graph
        const startImage2 = await flow.loadImageAnswer(form.startImage);
        graph.PreviewImage({ images: startImage2 });

        // Run new graph
        await flow.PROMPT();
```

**Comment by ricklove** [comment]
It also works fine to disable only part of the old graph: 

        // Run the graph you built
        const result = await flow.PROMPT();

        // Disable some nodes
        const iDisableStart = flow.workflow.nodes.indexOf(cropMask) + 1;
        flow.workflow.nodes.slice(iDisableStart).forEach((x) => x.disable());

        // Build new graph with part of old graph
        graph.PreviewImage({ images: cropMask.outputs.Heatmap$_Mask });

        // Run new graph
        await flow.PROMPT();

**Comment by rvion** [comment]
yes, the current refactoring I'm going to release soon is largely related to that. 

it includes:

- `graphs` will be renamed `ComfyWorkflows`
- no default `ComfyWofklow` instanciated by default.
- no more `flow.run()` by default
- if you want to build a ComfyUI workflow, you just do:
```
const graph = cushy.createComfyWofklow()
graph.PreviewImage({...})
await graph.PROMPT()

const someOtherGraph = cushy.createComfyWofklow()
const myWorkflowOne = cushy.createComfyWofklow()
...
```

**Comment by rvion** [comment]
> It also works fine to disable only part of the old graph:
> 
> ```
>     // Run the graph you built
>     const result = await flow.PROMPT();
> 
>     // Disable some nodes
>     const iDisableStart = flow.workflow.nodes.indexOf(cropMask) + 1;
>     flow.workflow.nodes.slice(iDisableStart).forEach((x) => x.disable());
> 
>     // Build new graph with part of old graph
>     graph.PreviewImage({ images: cropMask.outputs.Heatmap$_Mask });
> 
>     // Run new graph
>     await flow.PROMPT();
> ```

but this is also very nice. this method should totally live on the (currently named) `GraphL`. Graphs are indeed made to be manipulated, made dynamic, so one app can run the same workflow multiple times, mutating it along execution.
